### ISSUE TITLE
Not working with Ink Framework & WordPress

### ISSUE THREAD

**Issue by mewcrazy** [pMan/jQueryImageScroller#1]
Hello, I'm using the Ink Framework and WordPress. I successfully set up Imagescroller. The plugin even make changes to my div (top:-640px etc.) - But somehow it is not working like it should.

Could you please take a look and let me know how I can fix it?

http://v3.dennis-bitsch.de/portfolio/

Kind Regards,
Dennis Bitsch

**Comment by pMan** [comment]
Can you give me the link where you have hosted it?

Prasad (pMan <http://about.me/pman>) Cholakkottil
*Mobie: +91.9900.550.984*

**Comment by mewcrazy** [comment]
http://v3.dennis-bitsch.de/portfolio/

Here you can see it, its included.



Von meinem iPhone gesendet

**Comment by pMan** [comment]
I get an error "$ is not defined", I think you are using jQuery instead of
$. In that case, replace all $ in the plugin.
